// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXaEx4Ctvs84lkNXabJ-nCW1XOFTp4Ag',
    appId: '1:649826315759:android:26be105c4ffa4fa87e9a1a',
    messagingSenderId: '649826315759',
    projectId: 'baskat-leads',
    storageBucket: 'baskat-leads.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoZ7BVbco40afP7xZZOIuVOQ2k6tkm8dg',
    appId: '1:649826315759:ios:c86595f78adca00d7e9a1a',
    messagingSenderId: '649826315759',
    projectId: 'baskat-leads',
    storageBucket: 'baskat-leads.firebasestorage.app',
    iosBundleId: 'com.bastak.bastakLeads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmtMqiBMfokwsFiI-ZCApY9JBabkFLs9w',
    appId: '1:649826315759:web:e507cd608795b5b07e9a1a',
    messagingSenderId: '649826315759',
    projectId: 'baskat-leads',
    authDomain: 'baskat-leads.firebaseapp.com',
    storageBucket: 'baskat-leads.firebasestorage.app',
    measurementId: 'G-RWR5K2QEEQ',
  );
}
